### ISSUE TITLE
SSP additional properties in YAML header does get translated to OSCAL properties

### ISSUE THREAD

**Issue by jpower432** [oscal-compass/compliance-trestle#1518]
## Describe the bug

When a custom YAML header is used with `ssp generate` the `x-trestle-fedramp-props` and other metadata is not populated when running `ssp assemble`.

> Note: This is possibly behaving as intended in which case this should be converted to a feature request

## To Reproduce

For the reproduction steps, I am using the `compliance-trestle-ssp-demo` [repo](https://github.com/IBM/compliance-trestle-ssp-demo).

1. Create SSP Markdown with a custom YAML header
```
trestle author ssp-generate -cd ACME_comp_def --profile ACME_int_guidance --output md_ACME_platform_ssp -y assets/extra-ssp-metadata.yml
```
2. Edit the YAML header data for AC-1 located at `md_ACME_platform_ssp/ac/ac-1.md`

```
# Just editing the fedramp props
x-trestle-fedramp-props:
  control-origination:
    - Service provider System Specific
  implementation-status:
    - Implemented
```
3. Run `ssp-assemble`
```
trestle author ssp-assemble -m md_ACME_platform_ssp -cd ACME_comp_def -o ACME_SSP
```
4. Result is `No changes to assembled ssp so ssp not written out.`

## Expected behavior

FedRAMP property information is set on AC-1 Implemented Requirement

## Environment

OS: [e.g. iOS] Fedora 36
Python version: Python 3.10.11
Installed packages: Trestle version v2.5.1 based on OSCAL version 1.0.4
